FROM library/glassfish:4.1-jdk8
MAINTAINER Ivar Grimstad (ivar.grimstad@gmail.com)

ADD ./target/snoop-service-1.1.0-SNAPSHOT.war /usr/local/glassfish4/glassfish/domains/domain1/autodeploy/snoop-service-1.1.0-SNAPSHOT.war
